name: 'East Cape, Baja'
favicon: null
layout_spectrum: 0.16656587203033268
typography_spectrum: 0.7402454889379442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.349180412478745
  lightness: 0.5326209967024624
  saturation: 0.44393673446029425
  rhythmicContrast: 0.9708435270003974
purpose: []
